# Netlify configuration for the Vite-based React frontend in /client
# ────────────────────────────────────────────────────────────────
[build]
  # The frontend lives in the client/ sub-folder of the monorepo
  base    = "client"          # ↳ cd client && …
  command = "npm run build"   # ↳ vite build
  publish = "dist"            # ↳ Vite’s default output folder  [oai_citation:0‡Render](https://community.render.com/t/vite-app-build-folder-not-found/9516)

  # Optional: lock the Node version used during the build
  [build.environment]
    NODE_VERSION = "20"

# SPA fallback so React Router deep-links don’t 404 on refresh
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Optional: make `netlify dev` behave like `npm run dev`
[dev]
  framework   = "vite"
  targetPort  = 5173          # Vite’s default dev port
  command     = "npm run dev"
  autoLaunch  = false