version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: filemanager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Backend
    container_name: filemanager-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./Backend/public/uploads:/app/public/uploads  # for file storage, optional

volumes:
  pgdata:
